function radioRx = SDR_rx_init(SDRRx, SDRv, txInfo)

SDRRx.MasterClockRate = 20000000;  %Hz
% Radio values on lteSetParams
SDRRx.CenterFrequency    = SDRv.CenterFrequency;
SDRRx.Gain               = SDRv.RxRadioGain;
SDRRx.DecimationFactor   = 512;%2.*round((SDRRx.MasterClockRate/txInfo.SamplingRate)/2);

% Set up transmitter radio object to use the found radio
switch SDRRx.Platform
  case {'B200','B210'}
    radioRx = comm.SDRuReceiver(...
        'Platform',             SDRRx.Platform, ...
        'SerialNum',            SDRRx.Address, ...
        'MasterClockRate',      SDRRx.MasterClockRate, ...
        'CenterFrequency',      SDRRx.CenterFrequency,...
        'Gain',                 SDRRx.Gain, ...
        'DecimationFactor',     SDRRx.DecimationFactor,...
        'NumFramesInBurst',     SDRRx.NumFramesInBurst,...
        'EnableBurstMode',      true);
  case {'X300','X310'}
    radioRx = comm.SDRuReceiver(...
        'Platform',             SDRRx.Platform, ...
        'IPAddress',            SDRRx.Address, ...
        'MasterClockRate',      SDRRx.MasterClockRate, ...
        'CenterFrequency',      SDRRx.CenterFrequency,...
        'Gain',                 SDRRx.Gain, ...
        'DecimationFactor',      SDRRx.InterpolationFactor,...
        'NumFramesInBurst',     SDRRx.NumFramesInBurst,...
        'EnableBurstMode',      true);
  case {'N200/N210/USRP2'}
    radioRx = comm.SDRuReceiver(...
        'Platform',             SDRRx.Platform, ...
        'IPAddress',            SDRRx.Address, ...
        'CenterFrequency',      SDRRx.CenterFrequency,...
        'Gain',                 SDRRx.Gain, ...
        'DecimationFactor',      SDRRx.InterpolationFactor,...
        'NumFramesInBurst',     SDRRx.NumFramesInBurst,...
        'EnableBurstMode',      true);
end
