function radioTx = SDR_tx_init(SDRTx, SDRv, txInfo)

SDRTx.MasterClockRate = 1.92e6*4; %20000000;  %Hz
% Radio values on lteSetParams
SDRTx.CenterFrequency    = SDRv.CenterFrequency;
SDRTx.Gain               = SDRv.RadioGain;
SDRTx.InterpolationFactor= 2.*round((SDRTx.MasterClockRate/txInfo.SamplingRate)/2);

% Set up transmitter radio object to use the found radio
switch SDRTx.Platform
  case {'B200','B210'}
    radioTx = comm.SDRuTransmitter(...
        'Platform',             SDRTx.Platform, ...
        'SerialNum',            SDRTx.Address, ...
        'MasterClockRate',      SDRTx.MasterClockRate, ...
        'CenterFrequency',      SDRTx.CenterFrequency,...
        'Gain',                 SDRTx.Gain, ...
        'InterpolationFactor',  SDRTx.InterpolationFactor,...
        'UnderrunOutputPort',   true,...
        'ChannelMapping',       1);
  case {'X300','X310'}
    radioTx = comm.SDRuTransmitter(...
        'Platform',             SDRTx.Platform, ...
        'IPAddress',            SDRTx.Address, ...
        'MasterClockRate',      SDRTx.MasterClockRate, ...
        'CenterFrequency',      SDRTx.CenterFrequency,...
        'Gain',                 SDRTx.Gain, ...
        'InterpolationFactor',  SDRTx.InterpolationFactor,...
        'NumFramesInBurst',     SDRTx.NumFramesInBurst,...
        'EnableBurstMode',      false);
  case {'N200/N210/USRP2'}
    radioTx = comm.SDRuTransmitter(...
        'Platform',             SDRTx.Platform, ...
        'IPAddress',            SDRTx.Address, ...
        'CenterFrequency',      SDRTx.CenterFrequency,...
        'Gain',                 SDRTx.Gain, ...
        'InterpolationFactor',  SDRTx.InterpolationFactor,...
        'NumFramesInBurst',     SDRTx.NumFramesInBurst,...
        'EnableBurstMode',      false);
end
